//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPass_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int id { get; set; }
        public int candidateID { get; set; }
        public int employerID { get; set; }
        public System.DateTime appdate { get; set; }
        public int appstatusID { get; set; }
    
        public virtual Appstatuses Appstatuses { get; set; }
        public virtual Candidate Candidate { get; set; }
        public virtual Employer Employer { get; set; }
    }
}
