//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPass_Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CadrAgencyEntities : DbContext
    {
        public CadrAgencyEntities()
            : base("name=CadrAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Appstatuses> Appstatuses { get; set; }
        public virtual DbSet<Candidate> Candidate { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Levels> Levels { get; set; }
        public virtual DbSet<Networks> Networks { get; set; }
        public virtual DbSet<Resumes> Resumes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
        public virtual DbSet<Vacanciestatus> Vacanciestatus { get; set; }
    }
}
