//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPass_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumes
    {
        public int id { get; set; }
        public int vacancieID { get; set; }
        public int candidateID { get; set; }
        public int employerID { get; set; }
        public System.DateTime publicationdate { get; set; }
        public int looks { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual Vacancies Vacancies { get; set; }
    }
}
