//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashPass_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancies()
        {
            this.Resumes = new HashSet<Resumes>();
        }
    
        public int id { get; set; }
        public string vacancie { get; set; }
        public string describing { get; set; }
        public int salary { get; set; }
        public int skillID { get; set; }
        public int statusID { get; set; }
        public int employerID { get; set; }
    
        public virtual Employer Employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resumes> Resumes { get; set; }
        public virtual Skills Skills { get; set; }
        public virtual Vacanciestatus Vacanciestatus { get; set; }
    }
}
